// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package labx_subs

type Access struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Supplier  *Supplier `json:"supplier"`
	URL       *string   `json:"url"`
	User      *string   `json:"user"`
	CreatedAt string    `json:"createdAt"`
	UpdatedAt string    `json:"updatedAt"`
}

type AccessInput struct {
	Name     string  `json:"name"`
	Supplier string  `json:"supplier"`
	URL      *string `json:"url"`
	User     *string `json:"user"`
}

type Supplier struct {
	ID        string    `json:"id"`
	Code      string    `json:"code"`
	Name      string    `json:"name"`
	Accesses  []*Access `json:"accesses"`
	CreatedAt string    `json:"createdAt"`
	UpdatedAt string    `json:"updatedAt"`
}

type SupplierInput struct {
	Code string `json:"code"`
	Name string `json:"name"`
}
