// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package labx_subs

import (
	"labxsubs/model"
)

type AccessInput struct {
	Name     string  `json:"name"`
	Supplier string  `json:"supplier"`
	URL      *string `json:"url"`
	User     *string `json:"user"`
}

type Supplier struct {
	ID        string          `json:"id"`
	Code      string          `json:"code"`
	Name      string          `json:"name"`
	Accesses  []*model.Access `json:"accesses"`
	CreatedAt string          `json:"createdAt"`
	UpdatedAt string          `json:"updatedAt"`
}

type SupplierInput struct {
	Code string `json:"code"`
	Name string `json:"name"`
}
